# Generated by Django 6.0.8 on 2026-08-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tracks/album_covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='tracks/audio/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tracks/covers/'),
        ),
        migrations.AlterField(
            model_name='track',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tracks/video/'),
        ),
    ]
