# Generated by Django 6.0 on 2025-12-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_remove_track_audio_url_remove_track_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
