# Generated by Django 6.0 on 2026-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_alter_album_cover_alter_track_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='waveform_peaks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
