# Generated by GPT for Casset v2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0003_track_like_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="track",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="tracks", to="tracks.tag"),
        ),
    ]
