# Generated by GPT for Casset v2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0003_track_like_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("description", models.TextField(blank=True)),
                ("cover", models.ImageField(blank=True, null=True, upload_to="album_covers/")),
                ("content_type", models.CharField(choices=[("music", "Music"), ("podcast", "Podcast"), ("audiobook", "Audiobook"), ("video", "Video")], default="music", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("creator", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="albums", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(fields=("creator", "title", "content_type"), name="uniq_album_creator_title_type"),
        ),
        migrations.AddField(
            model_name="track",
            name="content_type",
            field=models.CharField(choices=[("music", "Music"), ("podcast", "Podcast"), ("audiobook", "Audiobook"), ("video", "Video")], default="music", max_length=16),
        ),
        migrations.AddField(
            model_name="track",
            name="album",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tracks", to="tracks.album"),
        ),
        migrations.AddField(
            model_name="track",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="track",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="track",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="video/"),
        ),
    ]
