# Generated by GPT for Casset v2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0004_album_and_track_content_fields"),
        ("tracks", "0004_tag_and_track_tags"),
    ]

    operations = []
