# Generated by GPT for Casset v2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracks", "0005_merge_20251219_0514"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="track",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
