# Generated by Django 6.0 on 2025-12-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0009_genre_per_content_and_book_format"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre",
            options={"ordering": ["content_type", "order", "name_fa"]},
        ),
        migrations.AlterField(
            model_name="album",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                    ("audiobook", "Audiobook"),
                    ("video", "Video"),
                ],
                default="music",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                    ("audiobook", "Audiobook"),
                    ("video", "Video"),
                ],
                default="music",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="genre",
            index=models.Index(
                fields=["content_type", "is_active", "parent", "order"],
                name="tracks_genr_content_db8b6c_idx",
            ),
        ),
    ]
