# Generated by Django 6.0 on 2025-12-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0009_genre_per_content_and_book_format"),
    ]

    # NOTE:
    # This migration existed due to a previous conflicting migration attempt.
    # It is intentionally kept as a NO-OP to preserve the migration graph.
    operations = []
