# Generated by Django 6.0 on 2025-12-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0010_alter_genre_options_remove_track_author_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="author_name",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="translator_name",
        ),
    ]
