# Generated by Django 6.0 on 2025-12-21 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0010_move_book_fields_to_track"),
        ("tracks", "0011_remove_genre_author_name_and_more"),
    ]

    operations = []
