# Generated by Django 6.0 on 2025-12-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0015_normalize_audiobook_genre_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name_fa',
            field=models.CharField(max_length=64),
        ),
    ]
