# Generated by ChatGPT for Casset: revert unintended audiobook genre slug normalization
from django.db import migrations


SLUG_MAP_FORWARD = {
    "business-audiobook": "business-book",
    "education-audiobook": "education-book",
    "psychology-audiobook": "psychology-book",
}

SLUG_MAP_BACKWARD = {v: k for k, v in SLUG_MAP_FORWARD.items()}


def _merge_or_rename_slug(apps, old_slug: str, new_slug: str):
    Genre = apps.get_model("tracks", "Genre")
    Track = apps.get_model("tracks", "Track")

    old = Genre.objects.filter(slug=old_slug).first()
    if not old:
        return

    new = Genre.objects.filter(slug=new_slug).first()
    if new and new.pk != old.pk:
        # Merge M2M relations so we don't lose track-genre links.
        through = Track.genres.through
        through.objects.filter(genre_id=old.pk).update(genre_id=new.pk)
        old.delete()
        return

    old.slug = new_slug
    old.save(update_fields=["slug"])


def forwards(apps, schema_editor):
    for old_slug, new_slug in SLUG_MAP_FORWARD.items():
        _merge_or_rename_slug(apps, old_slug=old_slug, new_slug=new_slug)


def backwards(apps, schema_editor):
    for old_slug, new_slug in SLUG_MAP_BACKWARD.items():
        _merge_or_rename_slug(apps, old_slug=old_slug, new_slug=new_slug)


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0015_normalize_audiobook_genre_slugs"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
