# Generated by Django 6.0 on 2025-12-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0017_alter_genre_name_fa'),
        ('tracks', '0017_revert_audiobook_genre_slug_normalization'),
    ]

    operations = [
    ]
