# Generated by Django 6.0.8 on 2026-08-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
