
# Generated by GPT for Casset v2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_billing_models"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="invoice", name="billing_inv_user_status"),
        migrations.RemoveIndex(model_name="invoice", name="billing_inv_valid_until"),
        migrations.DeleteModel(name="Transaction"),
        migrations.DeleteModel(name="Invoice"),
        migrations.DeleteModel(name="Plan"),
    ]
