
# Generated by GPT for Casset v2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_remove_invoice_billing_inv_user_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=40, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("price", models.PositiveIntegerField(default=0)),
                ("duration_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={"ordering": ["price"]},
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("paid", "Paid"), ("failed", "Failed"), ("canceled", "Canceled")], default="pending", max_length=16)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("provider_ref", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="billing.plan")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["user", "status"], name="billing_inv_user_status"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["valid_until"], name="billing_inv_valid_until"),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("create", "Create"), ("verify", "Verify"), ("webhook", "Webhook")], max_length=16)),
                ("status", models.CharField(choices=[("ok", "OK"), ("error", "Error")], max_length=16)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="billing.invoice")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
