# Generated by Django 6.0.8 on 2026-08-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsetting',
            name='auto_approve_tracks',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، محتوای ارسالی کاربران بدون بررسی دستی staff فوراً تایید و منتشر می\u200cشود (صف بررسی ترک دور زده می\u200cشود). برای شروع سریع\u200cتر و کاهش اصطکاک مناسب است؛ گزارش\u200cدهی کاربران (Report) کماکان فعال می\u200cماند.'),
        ),
    ]
