# Generated by Django 6.0 on 2026-08-17 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(max_length=64)),
                ("ua_hash", models.CharField(blank=True, max_length=64)),
                ("day_key", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("point_awarded", models.BooleanField(default=False)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_events",
                        to="tracks.track",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="play_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PointLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delta",
                    models.SmallIntegerField(
                        default=0,
                        help_text="+1 for award, 0 for blocked events (full audit trail).",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("play_reward", "Play reward"),
                            ("blocked_no_event", "Blocked: no play event"),
                            ("blocked_time", "Blocked: too fast"),
                            ("blocked_ip_limit", "Blocked: IP daily cap"),
                            ("blocked_duplicate", "Blocked: already awarded"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "track_id_snapshot",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Track ID at award time (denormalised for audit durability).",
                        null=True,
                    ),
                ),
                (
                    "ip_hash_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="IP hash at award time (denormalised).",
                        max_length=64,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Free-text detail added by system or staff.",
                        max_length=300,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "play_event",
                    models.OneToOneField(
                        blank=True,
                        help_text="The PlayEvent that triggered this entry (null for manual entries).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entry",
                        to="plays.playevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Creator who received (or was blocked from receiving) the point.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Point ledger entry",
                "verbose_name_plural": "Point ledger",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyTrackStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                ("plays", models.PositiveIntegerField(default=0)),
                ("unique_plays", models.PositiveIntegerField(default=0)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "ordering": ["-day"],
                "indexes": [
                    models.Index(fields=["track", "day"], name="plays_dts_track_day"),
                    models.Index(fields=["day"], name="plays_dts_day"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("track", "day"), name="uniq_daily_track_day"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FraudFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("play_burst", "Play burst (rate limit)"),
                            ("time_fraud", "Progress too fast"),
                            ("ip_day_limit", "IP daily award cap reached"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        default=1, help_text="Severity score. Higher = more suspicious."
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_flags",
                        to="tracks.track",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["flag_type", "created_at"],
                        name="plays_fraud_flag_ty_48fc37_idx",
                    ),
                    models.Index(
                        fields=["ip_hash", "created_at"],
                        name="plays_fraud_ip_hash_47a057_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="playevent",
            index=models.Index(
                fields=["track", "day_key"], name="plays_playe_track_i_909004_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playevent",
            index=models.Index(
                fields=["ip_hash", "day_key"], name="plays_playe_ip_hash_ca8f8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="playevent",
            constraint=models.UniqueConstraint(
                fields=("track", "ip_hash", "day_key"), name="uniq_play_track_ip_day"
            ),
        ),
        migrations.AddIndex(
            model_name="pointledger",
            index=models.Index(fields=["user", "created_at"], name="ledger_user_ts"),
        ),
        migrations.AddIndex(
            model_name="pointledger",
            index=models.Index(
                fields=["reason", "created_at"], name="ledger_reason_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="pointledger",
            index=models.Index(
                fields=["ip_hash_snapshot", "created_at"], name="ledger_ip_ts"
            ),
        ),
    ]
