# Generated by Django 6.0 on 2025-12-17 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0002_remove_track_audio_url_remove_track_cover_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('day_key', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_events', to='tracks.track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['track', 'day_key'], name='plays_playe_track_i_909004_idx'), models.Index(fields=['ip_hash', 'day_key'], name='plays_playe_ip_hash_ca8f8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('track', 'ip_hash', 'day_key'), name='uniq_play_track_ip_day')],
            },
        ),
    ]
