# Generated by Django 6.0.8 on 2026-08-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointledger',
            name='reason',
            field=models.CharField(choices=[('play_reward', 'Play reward'), ('payout_deduction', 'Payout deduction'), ('blocked_no_event', 'Blocked: no play event'), ('blocked_time', 'Blocked: too fast'), ('blocked_ip_limit', 'Blocked: IP daily cap'), ('blocked_duplicate', 'Blocked: already awarded')], max_length=32),
        ),
    ]
