# Generated by Django 6.0.8 on 2026-08-20 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_alter_pointledger_reason'),
        ('tracks', '0003_track_waveform_peaks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playevent',
            name='uniq_play_track_ip_day',
        ),
        migrations.AddConstraint(
            model_name='playevent',
            constraint=models.UniqueConstraint(fields=('track', 'user', 'ip_hash', 'day_key'), name='uniq_play_track_user_ip_day'),
        ),
    ]
