# Generated by GPT for Casset v2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plays", "0002_dailytrackstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="playevent",
            name="point_awarded",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(name="DailyTrackStat"),
    ]
