# Generated by GPT for Casset v2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plays", "0003_remove_dailytrackstat_plays_dts_track_day_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTrackStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField()),
                ("plays", models.PositiveIntegerField(default=0)),
                ("unique_plays", models.PositiveIntegerField(default=0)),
                ("points_awarded", models.PositiveIntegerField(default=0)),
                (
                    "track",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="daily_stats", to="tracks.track"),
                ),
            ],
            options={"ordering": ["-day"]},
        ),
        migrations.AddConstraint(
            model_name="dailytrackstat",
            constraint=models.UniqueConstraint(fields=("track", "day"), name="uniq_daily_track_day"),
        ),
        migrations.AddIndex(
            model_name="dailytrackstat",
            index=models.Index(fields=["track", "day"], name="plays_dts_track_day"),
        ),
        migrations.AddIndex(
            model_name="dailytrackstat",
            index=models.Index(fields=["day"], name="plays_dts_day"),
        ),
    ]
