# Generated by Django 6.0.8 on 2026-08-21 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_remove_playevent_uniq_play_track_ip_day_and_more'),
        ('tracks', '0003_track_waveform_peaks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointledger',
            name='reason',
            field=models.CharField(choices=[('play_reward', 'Play reward'), ('payout_deduction', 'Payout deduction'), ('blocked_no_event', 'Blocked: no play event'), ('blocked_time', 'Blocked: too fast'), ('blocked_ip_limit', 'Blocked: IP daily cap'), ('blocked_duplicate', 'Blocked: already awarded'), ('blocked_fraud_signal', 'Blocked: fraud signal (S11)')], max_length=32),
        ),
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=64)),
                ('ua_hash', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(default='web', help_text='Where the play originated: web, embed, api, progress_fallback, backfill.', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('qualified', 'Qualified (point awarded)'), ('flagged', 'Flagged (fraud signal / anomaly)'), ('closed', 'Closed (concluded without qualifying)')], default='open', max_length=16)),
                ('disqualify_reason', models.CharField(blank=True, help_text='Set when status=flagged: which signal/gate rejected this session.', max_length=120)),
                ('max_progress_ratio', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('play_event', models.ForeignKey(blank=True, help_text='The daily-dedup PlayEvent this attempt counted toward, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='plays.playevent')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_sessions', to='tracks.track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playback_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['track', 'user', 'started_at'], name='session_track_user_ts'), models.Index(fields=['ip_hash', 'started_at'], name='session_ip_ts'), models.Index(fields=['status', 'started_at'], name='session_status_ts')],
            },
        ),
    ]
