# Generated by Django 6.0 on 2025-12-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plays", "0005_fraudflag"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="fraudflag",
            new_name="plays_fraud_flag_ty_48fc37_idx",
            old_name="plays_fraud_flag_type_created",
        ),
    ]
