# Generated by Django 6.0.8 on 2026-08-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0005_backfill_playbacksession_from_playevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='playbacksession',
            name='country_code',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2, derived from a trusted CDN geo header. Empty if unknown.', max_length=2),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot/crawler'), ('unknown', 'Unknown')], default='unknown', max_length=16),
        ),
    ]
