
# Generated by GPT for Casset v2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0002_comments_favorites"),
    ]

    operations = [
        migrations.DeleteModel(name="CommentLike"),
        migrations.DeleteModel(name="Comment"),
        migrations.DeleteModel(name="TrackFavorite"),
    ]
