# Generated by Django 6.0.8 on 2026-08-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
