# Generated by Django 6.0 on 2026-08-17 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(db_index=True, max_length=32)),
                ("code_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=256)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["phone_number", "created_at"],
                        name="accounts_ph_phone_n_23b4c6_idx",
                    ),
                    models.Index(
                        fields=["phone_number", "is_used"],
                        name="accounts_ph_phone_n_f9d2ef_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=80)),
                ("bio", models.TextField(blank=True)),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="covers/"),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("points", models.IntegerField(default=0)),
                ("follower_count", models.PositiveIntegerField(default=0)),
                (
                    "primary_content_type",
                    models.CharField(
                        choices=[
                            ("music", "Music"),
                            ("podcast", "Podcast"),
                            ("audiobook", "Audiobook"),
                            ("video", "Video"),
                        ],
                        default="music",
                        max_length=16,
                    ),
                ),
                ("is_vip", models.BooleanField(default=False)),
                ("vip_until", models.DateTimeField(blank=True, null=True)),
                ("website_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("telegram_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                (
                    "public_handle",
                    models.SlugField(blank=True, max_length=30, null=True, unique=True),
                ),
                ("public_handle_set_at", models.DateTimeField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=32, null=True, unique=True),
                ),
                ("phone_verified_at", models.DateTimeField(blank=True, null=True)),
                ("onboarding_complete", models.BooleanField(default=False)),
                ("interests", models.JSONField(blank=True, default=list)),
                ("creator_enabled", models.BooleanField(default=False)),
                (
                    "creator_status",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
