# Generated by Django 6.0 on 2025-12-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
