# Generated by Django 6.0 on 2025-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_follower_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_vip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="vip_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
