# Generated by Django 6.0.8 on 2026-08-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_suspended_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/covers/'),
        ),
    ]
