
# Generated by GPT for Casset v2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_userprofile_avatar_url_userprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="primary_content_type",
            field=models.CharField(choices=[("music", "Music"), ("podcast", "Podcast"), ("audiobook", "Audiobook"), ("video", "Video")], default="music", max_length=16),
        ),
    ]
