# Generated by Django 6.0.8 on 2026-08-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_provider',
            field=models.CharField(choices=[('password', 'Password'), ('phone', 'Phone OTP'), ('google', 'Google')], default='password', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_sub',
            field=models.CharField(blank=True, help_text="Google's stable subject id. Immutable per Google account, unlike the email address — this is what we match on.", max_length=64, null=True, unique=True),
        ),
    ]
