
# Generated by GPT for Casset v2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_userprofile_primary_content_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="primary_content_type"),
    ]
