# Generated by Django 6.0 on 2025-12-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_userprofile_public_handle"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="phoneotp",
            new_name="accounts_ph_phone_n_23b4c6_idx",
            old_name="accounts_pho_phone_n_3d8a5f_idx",
        ),
        migrations.RenameIndex(
            model_name="phoneotp",
            new_name="accounts_ph_phone_n_f9d2ef_idx",
            old_name="accounts_pho_phone_n_6dbea3_idx",
        ),
    ]
