# Generated by Django 6.0 on 2025-12-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0010_rename_accounts_pho_phone_n_3d8a5f_idx_accounts_ph_phone_n_23b4c6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="primary_content_type",
            field=models.CharField(
                choices=[
                    ("music", "Music"),
                    ("podcast", "Podcast"),
                    ("audiobook", "Audiobook"),
                    ("video", "Video"),
                ],
                default="music",
                max_length=16,
            ),
        ),
    ]
