# Generated by Django 6.0 on 2025-12-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_normalize_primary_content_type'),
        ('accounts', '0012_userprofile_role_intent_kyc'),
    ]

    operations = [
    ]
