# Generated by GPT for Casset v2

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("explore", "0001_featured_pin"),
    ]

    operations = [
        migrations.DeleteModel(name="FeaturedPin"),
    ]
