# Generated by GPT for Casset v2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("explore", "0002_delete_featuredpin"),
        ("tracks", "0006_remove_track_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedPin",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_pins",
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="featuredpin",
            index=models.Index(fields=["is_active", "position"], name="exp_pin_active_pos"),
        ),
    ]
