
# Generated by GPT for Casset v2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracks", "0006_remove_track_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_type", models.CharField(choices=[("track", "Track"), ("profile", "Profile")], max_length=16)),
                ("reported_username", models.CharField(blank=True, max_length=150)),
                ("reason", models.CharField(choices=[("impersonation", "Impersonation / Username claim"), ("copyright", "Copyright"), ("spam", "Spam / Fake activity"), ("abuse", "Abuse / Harassment"), ("other", "Other")], max_length=32)),
                ("details", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("reviewed", "Reviewed"), ("actioned", "Actioned"), ("rejected", "Rejected")], default="pending", max_length=16)),
                ("admin_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reporter", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reports_made", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reports_reviewed", to=settings.AUTH_USER_MODEL)),
                ("target_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="reports_received", to=settings.AUTH_USER_MODEL)),
                ("track", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="reports", to="tracks.track")),
            ],
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(fields=["target_type", "status", "created_at"], name="moderation__target__1b6e16_idx"),
        ),
    ]
