# Generated by Django 6.0.8 on 2026-08-19 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='interactions.comment'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(choices=[('track', 'Track'), ('report', 'Report'), ('profile', 'Profile'), ('comment', 'Comment')], max_length=16),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('track', 'Track'), ('profile', 'Profile'), ('comment', 'Comment')], max_length=16),
        ),
    ]
