# Generated by Django 6.0.8 on 2026-08-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payoutrequest_points'),
        ('moderation', '0002_report_comment_alter_auditlog_target_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='billing.payoutrequest'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(choices=[('track', 'Track'), ('report', 'Report'), ('profile', 'Profile'), ('comment', 'Comment'), ('payout', 'Payout')], max_length=16),
        ),
    ]
