# Generated by Django 6.0 on 2025-12-19 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0003_auditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="moderation__target__f533b8_idx",
            old_name="moderation_audit_target_action_created",
        ),
    ]
