# Generated by Django 6.0 on 2025-12-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price_display',
            field=models.CharField(default='N/A', max_length=40),
        ),
    ]
