import os

from .base import *  # noqa: F401,F403

DEBUG = True

# Dev: secrets are auto-generated by base._require_secret if not in .env.
# Set them in .env to keep values stable across restarts.

# Dev security relax (never in prod)
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Show emails in console during development
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Django Debug Toolbar (install separately if needed)
INTERNAL_IPS = ["127.0.0.1"]
