import os
import sys

from .base import *  # noqa: F401,F403

DEBUG = True

# Test runs (manage.py test AND bare pytest) create dozens/hundreds of
# users; PBKDF2's deliberately-slow hashing turns that into minutes of
# wall-clock time for no security benefit in a throwaway test DB.
if "test" in sys.argv or "pytest" in sys.argv[0]:
    PASSWORD_HASHERS = ["django.contrib.auth.hashers.MD5PasswordHasher"]

# Dev: secrets are auto-generated by base._require_secret if not in .env.
# Set them in .env to keep values stable across restarts.

# Dev security relax (never in prod)
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Show emails in console during development
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Django Debug Toolbar (install separately if needed)
INTERNAL_IPS = ["127.0.0.1"]
