# Generated by Django 6.0 on 2026-08-17 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("interactions", "0001_initial"),
        ("tracks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("new_follower", "فالوور جدید"),
                            ("track_liked", "لایک ترک"),
                            ("track_comment", "کامنت جدید"),
                            ("comment_liked", "لایک کامنت"),
                            ("track_approved", "ترک تأیید شد"),
                            ("track_rejected", "ترک رد شد"),
                            (
                                "new_track_from_follow",
                                "ترک جدید از کسی که دنبال می\u200cکنی",
                            ),
                            ("milestone_plays", "مایل\u200cستون پخش"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "group_key",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("actor_count", models.PositiveIntegerField(default=1)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="interactions.comment",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="tracks.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notif_recipient_read_ts",
                    ),
                    models.Index(
                        fields=["group_key", "recipient"], name="notif_group_recipient"
                    ),
                ],
            },
        ),
    ]
