# Generated by Django 6.0 on 2026-08-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('new_follower', 'فالوور جدید'), ('track_liked', 'لایک ترک'), ('track_comment', 'کامنت جدید'), ('comment_liked', 'لایک کامنت'), ('track_approved', 'ترک تأیید شد'), ('track_rejected', 'ترک رد شد'), ('new_track_from_follow', 'ترک جدید از کسی که دنبال می\u200cکنی'), ('milestone_plays', 'مایل\u200cستون پخش'), ('track_reposted', 'بازنشر ترک')], db_index=True, max_length=32),
        ),
    ]
