# Generated by Django 6.0.8 on 2026-08-20 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_verb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_follower', models.BooleanField(default=True)),
                ('track_liked', models.BooleanField(default=True)),
                ('track_comment', models.BooleanField(default=True)),
                ('comment_liked', models.BooleanField(default=True)),
                ('new_track_from_follow', models.BooleanField(default=True)),
                ('milestone_plays', models.BooleanField(default=True)),
                ('track_reposted', models.BooleanField(default=True)),
                ('weekly_email_digest', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
